# Generated by Django 3.2 on 2021-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sort_desciption', models.TextField()),
                ('desciption', models.TextField()),
                ('photo', models.ImageField(upload_to='photo/')),
                ('creation', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
