# Generated by Django 3.2 on 2021-04-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(upload_to='media/photo/'),
        ),
    ]
